### ISSUE TITLE
add function that allows for forwarding its votium rewards

### ISSUE THREAD

**Issue by gosuto-inzasheru** [GalloDaSballo/vested-cvx#2]
there is an address forwarding function in the votium system which lets an address claim rewards on behalf of another address: https://docs.votium.app/explainers/address-forwarding

this will make it possible for the politician multisig to claim votium bribes directly, without needing dev msig or the vestedcvx strat.

on the `native.vestedCVX` strategy contract, `strategist` should be able to initiate a call from the strat to the votium registry (`0x92e6E43f99809dF84ed2D533e1FD8017eb966ee2`): `AddressRegistry.setRegistry(BRIBES_RECEIVER)`.

**Comment by Tritium-VLK** [comment]
@GalloDaSballo I think I can handle this via a core vote with Votium.  Talk to me before you start work on this ticket.

**Comment by GalloDaSballo** [comment]
Just spoke with Tritium, we most likely won't be delegating to the MULTI and most likely instead lower the security threshold for claiming (as we can prove that a claim is harmless and basically just saves gas)

Claiming throughs strat emits an event which allows an easier time tracking funds, giving more visibility to depositors (and everyone else)

As such we'll go through that flow, discuss with the rest of solidity team and then should be able to code up an upgrade by next Thursday

**Comment by gosuto-inzasheru** [comment]
awesome, that works too!

as long as claim can be initiated from politician multisig and support $cvx then all is good :)

**Comment by GalloDaSballo** [comment]
Replaced by allowing trustless claims via balance invariant checking
